version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DEV_POSTGRES_DB}
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "${DEV_DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
